### ISSUE TITLE
您好，图片识别不准，能手动纠正吗？

### ISSUE THREAD

**Issue by nodis** [greyovo/PicQuery#11]
您好：
      我的图搜APP存在以下几个问题：
1、搜出来的图片不全（我已经完整扫描了）；
2、搜索精度有待提升，如下图，我搜索猫头鹰，出现的图片各种各样都有

<details>
<summary>⚠️ 含有不适宜工作时浏览的内容</summary>
<img src="https://github.com/greyovo/PicQuery/assets/23695589/924fc607-a68d-4f1f-8f54-d5b0383b2217"/>
</details>

**Comment by greyovo** [comment]
不能手动矫正。
1，搜索不全是因为目前只限制了30个结果，后续考虑增加结果个数设置
2，这个目前没办法，应该是模型训练的数据集没有这样的数据
