### ISSUE TITLE
Fewer results than TIDY

### ISSUE THREAD

**Issue by edanweis** [greyovo/PicQuery#21]
I like the app, but why does it return fewer results than 
[https://github.com/slavabarkov/tidy](https://github.com/slavabarkov/tidy)?

Is it a different quantized model? 

It would be great to change model/index settings / threshold for similarity/dot product match, etc.

**Comment by jelychow** [comment]
Hi @edanweis, the issue has been fixed in the lastest version, could you please update your code and share your feedbacks?
