### ISSUE TITLE
Crashed while launching the APP

### ISSUE THREAD

**Issue by greyovo** [greyovo/PicQuery#4]
In some cases, as soon as the APP is launched, it will immediately crash without any alert or dialog.

**Comment by lingchen-jiager** [comment]
The same situation，but a little different，when the APP was launched, it did not immediately crash ，but when i started to Index the gallery the app  immediately crashed without any alert or dialog.


一样的情况 ：

红米k20pro 一索引图库就闪退，系统版本miui 12.5.6，6gb运行内存。

小米平板 pad5 pro，系统版本 miui pad 14.0.4 ，8g运存，同样一索引图库就闪退。

**Comment by greyovo** [comment]
@lingchen-jiager 感谢反馈。你的情况应该和 #2 相似，可以在 #2 中提供MIUI捕获的错误记录吗（一般在闪退后，MIUI系统状态栏会有提示，点击后可以复制错误信息），非常感谢

**Comment by lingchen-jiager** [comment]
我没在通知栏看到闪退的错误捕捉记录，所有无法提供。



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 15, 2023 10:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [greyovo/PicQuery] Crashed while launching the APP (Issue #4)




 
@lingchen-jiager 感谢反馈。你的情况应该和 #2 相似，可以在 #2 中提供MIUI捕获的错误记录吗（一般在闪退后，MIUI系统状态栏会有提示，点击后可以复制错误信息），非常感谢

**Comment by greyovo** [comment]
已解决。

原因：当外置存储中有图片时，`albumLabel` 为 `null`，会引起空指针错误。
```kt
albumLabel = cursor.getString(cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.BUCKET_DISPLAY_NAME))
```

旧版本的解决方式：将存储空间的根目录下的图片，移动到任意文件夹中。
