### ISSUE TITLE
 Instance creation error : could not create instance for '[Singleton:'me.grey.picquery.domain.encoder.ImageEncoder']': ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Invalid fd was supplied: -1

### ISSUE THREAD

**Issue by Alpha-chen** [greyovo/PicQuery#6]
first build source code ，crash。

` [Koin]                  me.grey.picquery                     E  * Instance creation error : could not create instance for '[Singleton:'me.grey.picquery.domain.encoder.ImageEncoder']': ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Invalid fd was supplied: -1
                                                                                                    	ai.onnxruntime.OrtSession.createSession(Native Method)
                                                                                                    	ai.onnxruntime.OrtSession.<init>(OrtSession.java:74)
                                                                                                    	ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:234)
                                                                                                    	ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:219)
                                                                                                    	me.grey.picquery.domain.encoder.ImageEncoder.<init>(ImageEncoder.kt:36)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$3.invoke(AppModules.kt:68)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$3.invoke(AppModules.kt:68)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$1.invoke(AppModules.kt:51)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:91)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:60)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:22)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel
2023-10-13 20:29:18.983 30179-30179 [Koin]                  me.grey.picquery                     E  * Instance creation error : could not create instance for '[Singleton:'me.grey.picquery.domain.ImageSearcher']': org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'me.grey.picquery.domain.encoder.ImageEncoder']'
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$1.invoke(AppModules.kt:51)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:91)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:60)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:22)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
                                                                                                    	me.grey.picquery.ui.home.HomeScreenKt.HomeScreen(HomeScreen.kt:264)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:34)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:33)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.navigation.compose.NavHos
2023-10-13 20:29:18.985 30179-30179 [Koin]                  me.grey.picquery                     E  * Instance creation error : could not create instance for '[Singleton:'me.grey.picquery.domain.AlbumManager']': org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'me.grey.picquery.domain.ImageSearcher']'
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:91)
                                                                                                    	me.grey.picquery.common.AppModulesKt$domainModules$1$2.invoke(AppModules.kt:60)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:22)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
                                                                                                    	me.grey.picquery.ui.home.HomeScreenKt.HomeScreen(HomeScreen.kt:264)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:34)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:33)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:320)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:318)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	androidx.navigation.compose.NavBackStackEnt
2023-10-13 20:29:18.987 30179-30179 [Koin]                  me.grey.picquery                     E  * Instance creation error : could not create instance for '[Factory:'me.grey.picquery.ui.home.HomeViewModel']': org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'me.grey.picquery.domain.AlbumManager']'
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:81)
                                                                                                    	me.grey.picquery.common.AppModulesKt$viewModelModules$1$1.invoke(AppModules.kt:22)
                                                                                                    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                                                                    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                                                                                                    	org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                                                                                                    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                                                                                                    	org.koin.core.scope.Scope.get(Scope.kt:212)
                                                                                                    	org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
                                                                                                    	me.grey.picquery.ui.home.HomeScreenKt.HomeScreen(HomeScreen.kt:264)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:34)
                                                                                                    	me.grey.picquery.ui.AppNavHostKt$AppNavHost$3$1.invoke(AppNavHost.kt:33)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:320)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:318)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:318)
                                                                                                    	androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:302)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	androidx.compose.animation.AnimatedContentKt$PopulateContentFor$5.invoke(AnimatedContent.kt:94`

**Comment by greyovo** [comment]
已定位问题，是 `ImageEncoder` `TextEncoder` 的模型文件名与 README 没有对应导致的，正在解决

**Comment by greyovo** [comment]
已更新README和代码。请参考README的说明重新运行JupyterBook中的脚本获取新的模型。

也可以在 [Google Drive](https://drive.google.com/drive/folders/1VHgEvYyKsiVte8-lywD8qS8SfgcvMc3z?usp=drive_link) 中直接下载模型并复制到assets中。
