### ISSUE TITLE
增加smb文件夹

### ISSUE THREAD

**Issue by africa1207** [greyovo/PicQuery#7]
大佬能否支持局域网smb文件夹或者webdav啥的，因为图片都是放到群晖里面的

**Comment by greyovo** [comment]
你可能需要： [MT-Photos](https://mtmt.tech/)

**Comment by africa1207** [comment]
> 你可能需要： [MT-Photos](https://mtmt.tech/)

虽然支持openai clip模型以文搜图，但这个又是一套单独的相册系统了

**Comment by greyovo** [comment]
图搜实现以文搜图的前提是要对所有图片事先获取特征向量，也就是要获取到图片源文件（或缩略图）。如果要支持局域网里其他图片，实际上还是要把图片都下载下来，这样就意义不大了。

更合理的方式应当是，在 NAS 或者服务器上对图片进行这个操作，然后提供接口给用户进行搜索。这就不属于一个APP能做的事情了。
