### ISSUE TITLE
有win10版本的吗

### ISSUE THREAD

**Issue by yishujiahuanxiang** [greyovo/PicQuery#8]

**Comment by greyovo** [comment]
暂时没有这个计划

**Comment by Jackxwb** [comment]
[CLIP-ImageSearch-NCNN](https://github.com/EdVince/CLIP-ImageSearch-NCNN)
可以在github里面找找，这是我之前找到的，不过作者没做持久化处理，也就是说关掉了就要重新扫描一遍图库，而且搜索结果只能出来一张图片，更接近demo吧ヾ(≧▽≦*)o
